basePath = "go.mlcdf.fr"

[index]
description = ""
extra_head = ""
title = "Maxime's go packages"

[repos]

[repos."/envpath"]
name = "envpath"
repo = "https://github.com/mlcdf/envpath"

[repos."/vanity-imports"]
name = "vanity-imports"
repo = "https://github.com/mlcdf/vanity-imports"
