basePath = "go.mlcdf.fr"

[index]
title = """Go packages by <a href="https://mlcdf.fr">mlcdf</a>"""

[repos]

[repos."/envpath"]
name = "envpath"
repo = "https://github.com/mlcdf/go"

[repos."/vanity-imports"]
name = "vanity-imports"
repo = "https://github.com/mlcdf/vanity-imports"
