basePath = "go.mlcdf.fr"

[index]
description = ""
extra_head = ""
title = "Maxime's go packages"

[repos]

[repos."/go"]
name = "go"
repo = "https://github.com/mlcdf/go"

[repos."/vanity-imports"]
name = "vanity-imports"
repo = "https://github.com/mlcdf/vanity-imports"
