domain = "go.mlcdf.fr"

[index]
title = "Go Modules — mlcdf"

[repos]

[repos."/sc-backup"]
repo = "https://github.com/mlcdf/sc-backup"

[repos."/dyndns"]
repo = "https://github.com/mlcdf/dyndns"

[repos."/vanity-imports"]
repo = "https://github.com/mlcdf/vanity-imports"

[repos."/logging"]
repo = "https://github.com/mlcdf/go.git/logging"

[repos."/envpath"]
repo = "https://github.com/mlcdf/go.git/envpath"
