domain = "go.mlcdf.fr"

[index]
title = "Go Modules — mlcdf"

[repos]

[repos."/sc-backup"]
repo = "https://github.com/mlcdf/sc-backup"

[repos."/dyndns"]
repo = "https://github.com/mlcdf/dyndns"

[repos."/vanity-imports"]
repo = "https://github.com/mlcdf/vanity-imports"

[repos."/go"]
repo = "https://github.com/mlcdf/go"
